### ISSUE TITLE
tar error on ubuntu-latest

### ISSUE THREAD

**Issue by richm** [ludeeus/action-shellcheck#102]
## Describe the issue

Here is the workflow file: https://github.com/linux-system-roles/firewall/actions/runs/9943312786/workflow?pr=227

to wit

```
jobs:
  shellcheck:
    runs-on: ubuntu-latest
...
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ShellCheck
        id: shellcheck_id
        uses: ludeeus/action-shellcheck@master
```

The log: https://github.com/linux-system-roles/firewall/actions/runs/9943312786/job/27466833505?pr=227

The error:

```
  curl -Lso "/home/runner/work/_actions/ludeeus/action-shellcheck/master/sc.tar.xz" \
    "${baseurl}/${INPUT_VERSION}/shellcheck-${INPUT_VERSION}.${osvariant}.x86_64.tar.xz"
  
  tar -xf "/home/runner/work/_actions/ludeeus/action-shellcheck/master/sc.tar.xz" -C "/home/runner/work/_actions/ludeeus/action-shellcheck/master"
  mv "/home/runner/work/_actions/ludeeus/action-shellcheck/master/shellcheck-${INPUT_VERSION}/shellcheck" \
    "/home/runner/work/_actions/ludeeus/action-shellcheck/master/shellcheck"
...
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

maybe something changed recently in ubuntu-latest, and now `tar -xf` does not automatically recognize the .xz extension and use the xz decompresser?

### Links

- **Link to action run:**
- **Link to action configuration:**
