### ISSUE TITLE
Option scandir doesn't work

### ISSUE THREAD

**Issue by Bablzz** [ludeeus/action-shellcheck#29]
Hi there!

Thanks for shellcheck

I had tried use scandir option when got message 
```
find: unrecognized: compose_test.go
```

My .yml
```
 - uses: actions/checkout@v2
 - name: Run ShellCheck
   uses: ludeeus/action-shellcheck@master
   with:
      scandir: './scripts'
      check_together: 'yes'
```

I've tried variant like  **scandir: 'scripts'** but got error again

Could you help me?

Thanks for advance
