### ISSUE TITLE
How to ignore multiple paths

### ISSUE THREAD

**Issue by mads256h** [ludeeus/action-shellcheck#32]
## Describe the issue

How do i ignore multiple paths?

**Comment by simeg** [comment]
You ignore it by doing

```yaml
...
    steps:
    - uses: actions/checkout@v2
    - name: Shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        ignore: dir1 dir2 dir3  # Ignore dir1, dir2 and dir3
```
