### ISSUE TITLE
No annotations created for problems with severity "note"

### ISSUE THREAD

**Issue by amezin** [ludeeus/action-shellcheck#46]
## Describe the issue

In the default configuration, no annotations are created for "notes".

I guess it's because Github Actions don't understand what "note" is - https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md:

> severity: a group number containing either 'warning' or 'error' case-insensitive. Defaults to `error`

### Links

- **Link to action run:** https://github.com/amezin/gnome-shell-extension-ddterm/runs/2639521628
- **Link to action configuration:** https://github.com/amezin/gnome-shell-extension-ddterm/blob/a5db87a01654cc571fb6f790d52641fa4f7d1a82/.github/workflows/lint.yml#L34-L39

**Comment by amezin** [comment]
https://docs.github.com/en/rest/reference/checks#annotations-items suggests that `notice` may be supported too (but not `note` that shellcheck outputs)

**Comment by avindra** [comment]
I switched to https://github.com/bewuethr/shellcheck-action and it works out of the box

**Comment by amezin** [comment]
> I switched to https://github.com/bewuethr/shellcheck-action and it works out of the box

I haven't tried it (yet) but it looks like that action doesn't implement annotations at all

**Comment by evulhotdog** [comment]
> > I switched to [bewuethr/shellcheck-action](https://github.com/bewuethr/shellcheck-action) and it works out of the box
> 
> I haven't tried it (yet) but it looks like that action doesn't implement annotations at all

Just verified it does not.

**Comment by evulhotdog** [comment]
Reviewdog supports it, if you want shellcheck w/ Github Annotations.

```
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "." # Optional.
          pattern: "*.sh" # Optional.
          filter_mode: nofilter # Optional.
          fail_on_error: true
```
