### ISSUE TITLE
How to add shellcheck flags?

### ISSUE THREAD

**Issue by angristan** [ludeeus/action-shellcheck#5]
How do I add a flag to the action? Like `-e SC1091`.

I tried this:

```yml
on: push
name: ShellCheck
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        args: -e SC1091
```

but it has no effect.
