### ISSUE TITLE
Not seeing annotations

### ISSUE THREAD

**Issue by pbrisbin** [ludeeus/action-shellcheck#55]
## Describe the issue

I'm probably doing something wrong, but I can't seem to get annotations out of the problem-matcher.

Here's a run,

![](https://files.pbrisbin.com/screenshots/screenshot.458009.png)

But no annotation for that warning is captured.

![](https://files.pbrisbin.com/screenshots/screenshot.458054.png)

### Links

(Sorry, private repository)

Config,

```yaml
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: ${{ matrix.scripts }}
          severity: warning

          # This is passed to find, so using this option (istead of the intended
          # paths) will make ShellCheck run on all files in the directory
          additional_files: '-true'
```
