### ISSUE TITLE
Windows not supported / or bug

### ISSUE THREAD

**Issue by Amet13** [ludeeus/action-shellcheck#57]
## Describe the issue

Trying to run it on Windows machine, but it's not working.
<img width="997" alt="Screenshot 2022-03-26 at 17 48 35" src="https://user-images.githubusercontent.com/5184847/160247112-5fb07146-5cf9-4e7d-b754-6edcc030a3ce.png">

```
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
```
