### ISSUE TITLE
RFC: Branch syntax

### ISSUE THREAD

**Issue by matthewpersico** [ludeeus/action-shellcheck#63]
## Describe the issue

If instead of, as in your example:
```
on:
  push:
    branches:
      - master
```
I have:
```
on: [push]
```
does the `uses` line become just 
```
      uses: ludeeus/action-shellcheck
```
or do I have to use some macro to specify the current branch? What macro might that be?
