### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by bostonaholic** [ludeeus/action-shellcheck#69]
## Describe the issue

When using this action in my project, the action prints a deprecation notice that `set-output` is deprecated.

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

My shellcheck action is pretty standard:

```
on: push

name: 'Trigger: Push action'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
```
