### ISSUE TITLE
Can we pls get moving tags?

### ISSUE THREAD

**Issue by mxcl** [ludeeus/action-shellcheck#91]
We use this action across 10+ projects and would like to get updates without having to manually do it.

The convention is a v2 tag that is moved when the version updates.

We use:

```yaml
- uses: fischerscode/tagger@v0
```

for this to do it automatically. Thanks for your consideration.

**Comment by jcbhmr** [comment]
This is a good idea! I don't like using `@master`. We use https://github.com/actions/publish-action like:

```yml
name: Update tags
on:
  release:
    types: [released]
concurrency:
  group: update-tags
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  update-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/publish-action@v0.2.2
        with:
          source-tag: ${{ github.event.release.tag_name }}
```
