### ISSUE TITLE
Clarify is globbing is allowed when ignoring paths and names

### ISSUE THREAD

**Issue by lindhe** [ludeeus/action-shellcheck#94]
## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

The documentation should be clearer (with examples) whether or not `ignore_paths` and `ignore_names` can take glob patterns and/or regex.

## Implementation

If it's not supported, clarify that.

If it is supported, include an example like:

```yaml
    ...
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        ignore_paths: >-
          ignoreme
          ignoremetoo
        ignore_names: >-
          ignorable.sh
          .zsh*
```
